INSERT INTO Customer (id, name) VALUES (1, 'John Smith')
INSERT INTO Customer (id, name) VALUES (2, 'Jack Black')
INSERT INTO Customer (id, name) VALUES (3, 'Jason Brown')
INSERT INTO Customer (id, name) VALUES (4, 'Mary Doe')
INSERT INTO Customer (id, name) VALUES (5, 'Jane Doe')
INSERT INTO Customer (id, name) VALUES (6, 'Bill Smith')
INSERT INTO Customer (id, name) VALUES (7, 'Bob Smith')
INSERT INTO Customer (id, name) VALUES (8, 'Mary Brown')